name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: |
          bun install
          bun run docs
          bun run docs:json

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          commit_message: 'docs: update'
